// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUlkr-rOjDKGb-2PHvPXP1V5BYu-l_avE',
    appId: '1:809364461679:web:f6e9286edaa30efd42d59a',
    messagingSenderId: '809364461679',
    projectId: 'adekunle-project',
    authDomain: 'adekunle-project.firebaseapp.com',
    databaseURL: 'https://adekunle-project.firebaseio.com',
    storageBucket: 'adekunle-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJnXoqCP2I2pXzJoe360sB_vnBIU99CCU',
    appId: '1:809364461679:android:2633665dd50bb3bb42d59a',
    messagingSenderId: '809364461679',
    projectId: 'adekunle-project',
    databaseURL: 'https://adekunle-project.firebaseio.com',
    storageBucket: 'adekunle-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5QDf07rrLsqyBdGdsQ3B8yeYV2hLKe7Q',
    appId: '1:809364461679:ios:532a4aec59a23a0b42d59a',
    messagingSenderId: '809364461679',
    projectId: 'adekunle-project',
    databaseURL: 'https://adekunle-project.firebaseio.com',
    storageBucket: 'adekunle-project.firebasestorage.app',
    iosBundleId: 'com.example.wellnessDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5QDf07rrLsqyBdGdsQ3B8yeYV2hLKe7Q',
    appId: '1:809364461679:ios:532a4aec59a23a0b42d59a',
    messagingSenderId: '809364461679',
    projectId: 'adekunle-project',
    databaseURL: 'https://adekunle-project.firebaseio.com',
    storageBucket: 'adekunle-project.firebasestorage.app',
    iosBundleId: 'com.example.wellnessDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUlkr-rOjDKGb-2PHvPXP1V5BYu-l_avE',
    appId: '1:809364461679:web:15dd84dbde25239b42d59a',
    messagingSenderId: '809364461679',
    projectId: 'adekunle-project',
    authDomain: 'adekunle-project.firebaseapp.com',
    databaseURL: 'https://adekunle-project.firebaseio.com',
    storageBucket: 'adekunle-project.firebasestorage.app',
  );
}
